apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-chart
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status.github: ""
spec:
  project: local
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
  source:
    path: "root-chart"
    repoURL: https://github.com/mostmm/gitops.git
    targetRevision: main
    helm:
      valueFiles:
        - values.yaml
