apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-dashboard-{{ .Values.env }}
  labels:
    grafana_dashboard: "1"
data:
{{ (.Files.Glob "files/fastapi-dashboard*.json").AsConfig | indent 2 }}
