apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-dashboard-{{ .Values.env }}
  labels:
    grafana_dashboard: "1"
data:
{{ (.Files.Glob (printf "files/fastapi-dashboard%s.json" .Values.env)).AsConfig | indent 2 }}
