apiVersion: v1
kind: ConfigMap
metadata:
  name: fastapi-dashboard
  labels:
    grafana_dashboard: "1"
data:
  fastapi-dashboard.json:
{{ (.Files.Glob "files/fastapi-dashboard.json").AsConfig | indent 2 }}
