apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-app-{{ .Values.env }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi-app-{{ .Values.env }}
  template:
    metadata:
      labels:
        app: fastapi-app-{{ .Values.env }}
    spec:
      containers:
      - name: fastapi-app-{{ .Values.env }}
        image: rslim087/fastapi-prometheus:latest
        ports:
        - containerPort: 8000
          name: web