apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-app
  labels:
    release: {{ .Values.ServiceMonitor.release }}
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
  - port: web
    path: /metrics
    interval: 15s