apiVersion: v1
kind: Service
metadata:
  name: fastapi-app-{{ .Values.env }}
  labels:
    app: fastapi-app-{{ .Values.env }}
spec:
  selector:
    app: fastapi-app-{{ .Values.env }}
  ports:
  - port: 8000
    targetPort: 8000
    name: web
