apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: fastapi-app
  labels:
    release: {{- toYaml (index $.Values.apps $app.name).$env.ServiceMonitor.release | nindent 8 }}
spec:
  selector:
    matchLabels:
      app: fastapi-app
  endpoints:
  - port: web
    path: /metrics
    interval: 15s