defaults:
  project: local
  server: https://kubernetes.default.svc
  namespace: argocd
  selfHeal: true
  prune: true

apps:
  mock-app:
    namespace: mock-app
    name: mock-app
    repoUrl: https://github.com/mostmm/gitops.git

    envs:
      test:
        enabled: true
        values:
          ServiceMonitor:
            release: prometheus

      prod:
        enabled: true
        values:
          ServiceMonitor:
            release: kube-prometheus
