{{- range $chartIndex, $app := .Values.apps }}
{{- range $envIndex, $env := $app.envs }}
{{- if $env.enabled }}

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $app.name }}
  namespace: {{ $.Values.defaults.namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-status.github: ""
spec:
  project: {{ $.Values.defaults.project }}
  destination:
    server: {{ $.Values.defaults.server }}
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: {{ $app.selfHeal | default $.Values.defaults.selfHeal }}
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: {{ $app.repoUrl }}
    path: "{{ $app.path | default $app.name }}/{{ $envIndex }}"
    targetRevision: "ft/charted"
    helm:
      values: |
        {{- toYaml $env.values | nindent 8 }}

{{- end }}
{{- end }}
{{- end }}
